### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by apo-mak**
Update "JELLYFIN_FFMPEG_VERSION"  to a version that add support for :
"Add oneVPL runtime for QSV on 12th Gen Intel processors"

# Pull request

## CLA

- [x] I agree that by opening a pull requests I am handing over copyright ownership 
of my work contained in that pull request to the Unmanic project and the project 
owner. My contribution will become licensed under the same license as the overall project. 
This extends upon paragraph 11 of the Terms & Conditions stipulated in the GPL v3.0

## Checklist 

- [x] I have ensured that my pull request is being opened to merge into the staging branch.

- [x] I have ensured that all new python file contributions contain the correct header as 
stipulated in the [Contributing Docs](CONTRIBUTING.md).

## Description of the pull request

Update "JELLYFIN_FFMPEG_VERSION"  to a version that add support for :
"Add oneVPL runtime for QSV on 12th Gen Intel processors"

### CODE REVIEW

**Comment by Josh5** [comment]
Do you know if this update affects older Intel CPUs? Last time I updated I rolled it back because other users were unable to use vaapi on their installs that had previously been working.

**Comment by apo-mak** [comment]
I try it in my system (VM) with a xeon E5540 but not totally sure because it is a hyper-v setup and the cpu is virtualized and some times this crates a compatibility layer and dose not directly pass the cpu .

**Comment by Josh5** [comment]
I would love to do some in-depth testing of this before it gets rolled out to everyone. I'll run some tests on my CPU, but it will probably work. The ones that had issues were the Intel Celeron CPUs that most people using Unmanic on a NAS have.

In the meantime, did you know that you can add startup scripts to the container that get executed when the container starts.
You could add this to it just for your setup.
It would be something like:
```
#      _      _ _        __ _         _____ _____
#     | | ___| | |_   _ / _(_)_ __   |  ___|  ___| __ ___  _ __   ___  __ _
#  _  | |/ _ \ | | | | | |_| | '_ \  | |_  | |_ | '_ ` _ \| '_ \ / _ \/ _` |
# | |_| |  __/ | | |_| |  _| | | | | |  _| |  _|| | | | | | |_) |  __/ (_| |
#  \___/ \___|_|_|\__, |_| |_|_| |_| |_|   |_|  |_| |_| |_| .__/ \___|\__, |
#                 |___/                                   |_|         |___/
#
JELLYFIN_FFMPEG_VERSION="4.4.1-3"

if [[ ! -f /config/jellyfin-ffmpeg_${JELLYFIN_FFMPEG_VERSION}-focal_amd64.deb ]]; then
    curl -ksL -o /config/jellyfin-ffmpeg_${JELLYFIN_FFMPEG_VERSION}-focal_amd64.deb \
        "https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/${JELLYFIN_FFMPEG_VERSION}/jellyfin-ffmpeg_${JELLYFIN_FFMPEG_VERSION}-focal_amd64.deb"
fi

# Install updated jellyfin if version does not match
current_version=$(dpkg -s jellyfin-ffmpeg | grep '^Version:' | awk '{print $2}')
if [[ ${current_version} != "${JELLYFIN_FFMPEG_VERSION}-focal" ]]; then
    apt-get install -y /config/jellyfin-ffmpeg_${JELLYFIN_FFMPEG_VERSION}-focal_amd64.deb
fi

```

Similar to how Filebot is installed in the container in this guide: https://docs.unmanic.app/docs/guides/filebot_post_processor

**Comment by martadinata666** [comment]
For references this thread specifically call out about the transcoding issue with older hardware, older than gen 8
https://github.com/jellyfin/jellyfin-ffmpeg/issues/99

The solution it get is to specifically set LIBVA type to environment, as by default it use newer iHD instead i965
https://github.com/jellyfin/jellyfin/pull/7397

Can't really tell if it work on container ENV.

**Comment by Josh5** [comment]
After some internal testing, we have just bumped ffmpeg to v6

**Pull request closed without merging**
