### PR TITLE
versionless docker file

### PR DESCRIPTION
**Pull request by nadinio**
# Pull request

## CLA

- [x] I agree that by opening a pull requests I am handing over copyright ownership 
of my work contained in that pull request to the Unmanic project and the project 
owner. My contribution will become licensed under the same license as the overall project. 
This extends upon paragraph 11 of the Terms & Conditions stipulated in the GPL v3.0

## Checklist 

- [x] I have ensured that my pull request is being opened to merge into the staging branch.

- [x] I have ensured that all new python file contributions contain the correct header as 
stipulated in the [Contributing Docs](CONTRIBUTING.md).

## Description of the pull request
Removing versions from the runtime dependencies and Intel media drivers. This should shift the responsibilities of maintaining the appropriate versions to the package managers rather than the Unmanic maintainers

### CODE REVIEW

**Comment by Josh5** [comment]
Why remove the versions?
These are locked so that the dependencies do not change unexpectedly between builds. If there is one out of date, I would prefer to update just that version.

Alternatively, you have the option to run a startup script that you can use to apt update your dependencies if you wish.

**Comment by nadinio** [comment]
For a few reasons, removing the version numbers removes the responsibility for us to maintain the version numbers. Additionally, these packages can be updated fairly frequently to address bugs or security vulnerabilities that may exist in an older version.

**Comment by Josh5** [comment]
This is not a good way to make docker images.
I have a script that I usually run prior to publishing new releases that shows me what has been updated. From there I can easily maintain this. Considering I am the only maintainer of this docker image, I see no issue keeping things updated in the current structured way.

I know that this unmanic docker does not strictly follow best practices for building docker images, but those deviations provide users with more freedom to customise the container to their needs. Removing fixed versions on dependencies does not provide anything for end users that they don't already get.

A better approach in my mind would be to remove FFmpeg and all of these drivers from the container and develop a system in Unmanic for installing tools as required by the end user. That actually would be less work for me as a maintainer of this project.

**Comment by Ornias1993** [comment]
> For a few reasons, removing the version numbers removes the responsibility for us to maintain the version numbers. Additionally, these packages can be updated fairly frequently to address bugs or security vulnerabilities that may exist in an older version.

Normally project use a CI pipeline, like @Josh5 explained, to update dependencies. That way tests can also be run when dependencies are updated and the version updates are clearly documented when things break.

This is basically a best-practice and this PR is in contrast to said best practice

TLDR: PR can get closed, bad design choice.

@Josh5 On the topic of maintenance/testing:
Some fusstesting might be interesting to test the FFmpeg stack though...
(aka run tests using randomised ffmpeg encoding settings)

**Comment by Josh5** [comment]
@Ornias1993 I'd be happy to include any testing that people submit!
Testing things like FFmpeg or the packages mentioned in this PR is really hard. I have found that if you introduce testing, you really need to be testing against hardware rather than in a CI. So for things like updating the intel media drivers or even the FFmpeg version, you really need to test that on a wide spread of intel CPUs.

The thought of creating a set of containers that target specific CPU hardware has crossed my mind. But I am very limited in what I personally can develop or test for. Hence, I would be really happy for the community to pitch in and help with any testing. Perhaps even take ownership on creating some targeted Docker images that are designed for specific hardware that I don't have...

**Comment by Ornias1993** [comment]
> @Ornias1993 I'd be happy to include any testing that people submit! Testing things like FFmpeg or the packages mentioned in this PR is really hard. I have found that if you introduce testing, you really need to be testing against hardware rather than in a CI. So for things like updating the intel media drivers or even the FFmpeg version, you really need to test that on a wide spread of intel CPUs.
> 
> The thought of creating a set of containers that target specific CPU hardware has crossed my mind. But I am very limited in what I personally can develop or test for. Hence, I would be really happy for the community to pitch in and help with any testing. Perhaps even take ownership on creating some targeted Docker images that are designed for specific hardware that I don't have...

TLDR: i think your images are fine.

**Pull request closed without merging**
