### PR TITLE
[DOCKER] Bump Jellyfin FFmpeg version to 5.1.3-1 and update runtime libs

### LINKED ISSUE #396: QSV fails on Intel Arc A380
### Description

When trying to trying to use QSV with Unmanic on some files, I get the following error:
```
[AVHWDeviceContext @ 0x556979e51280] libva: /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so init failed

[AVHWDeviceContext @ 0x556979e51280] Failed to initialise VAAPI connection: 1 (operation failed).

Device creation failed: -5.

Failed to set value 'qsv=hw' for option 'init_hw_device': Input/output error

Error parsing global options: Input/output error
```

### Steps to Reproduce

1. Install Unmanic on UnRaid
2. Make sure you're using Kernel 6.2, Intel GPU Top plugin and device is passed through to the container
3. Force transcode in Jellyfin, make sure it works
4. Try transcoding something with the QSV plugin in Unmanic
5. See failure above

**Expected behavior:**
Just as in Jellyfin, with the GPU passed through to the container, it should be able to use ffmpeg to transcode

**Actual behaviour:**
It throws the above error. I suspect an older version of ffmpeg is used. The latest jellyfin binary is at 6.x. I noticed some Unmanic patch notes mentioning 4.4 or similar.

### Versions

Current release of the Unraid docker image.

### PR DESCRIPTION
**Pull request by nyanmisaka**
[Someone on reddit](https://www.reddit.com/r/jellyfin/comments/12tijk6/is_there_meaningful_difference_between_ffmpeg_and/) let me know that Unmanic is using an outdated jellyfin-ffmpeg. So here comes a PR to update it.

Btw the outdated Mesa and Intel libs from Ubuntu repo are not required anymore since our deb package comes with the latest one that used in our Jellyfin server.

And if anyone is interested in AV1 hardware encoding, you can give `jellyfin-ffmpeg6` a try.

# Pull request

## CLA

- [x] I agree that by opening a pull requests I am handing over copyright ownership 
of my work contained in that pull request to the Unmanic project and the project 
owner. My contribution will become licensed under the same license as the overall project. 
This extends upon paragraph 11 of the Terms & Conditions stipulated in the GPL v3.0

## Checklist 

- [x] I have ensured that my pull request is being opened to merge into the staging branch.

- [x] I have ensured that all new python file contributions contain the correct header as 
stipulated in the [Contributing Docs](CONTRIBUTING.md).

## Description of the pull request

fixes #396 #384

```
root@ceb94c106c63:/# ffmpeg -v verbose -init_hw_device vaapi=va -init_hw_device qsv@va -init_hw_device opencl@va -init_hw_device vulkan@va
ffmpeg version 5.1.3-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[AVHWDeviceContext @ 0x556f1ac9ac80] Trying to use DRM render node for device 0.
[AVHWDeviceContext @ 0x556f1ac9ac80] libva: VA-API version 1.18.0
[AVHWDeviceContext @ 0x556f1ac9ac80] libva: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x556f1ac9ac80] libva: Found init function __vaDriverInit_1_18
[AVHWDeviceContext @ 0x556f1ac9ac80] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x556f1ac9ac80] Initialised VAAPI connection: version 1.18
[AVHWDeviceContext @ 0x556f1ac9ac80] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 23.1.6 (8589406).
[AVHWDeviceContext @ 0x556f1ac9ac80] Driver not found in known nonstandard list, using standard behaviour.
[AVHWDeviceContext @ 0x556f1acc9180] Initialize MFX session: API version is 1.35, implementation version is 1.255
[AVHWDeviceContext @ 0x556f1adbc8c0] 0.0: Intel(R) OpenCL HD Graphics / Intel(R) Graphics [0x56a5]
[AVHWDeviceContext @ 0x556f1adbc8c0] Intel QSV to OpenCL mapping function found (clCreateFromVA_APIMediaSurfaceINTEL).
[AVHWDeviceContext @ 0x556f1adbc8c0] Intel QSV in OpenCL acquire function found (clEnqueueAcquireVA_APIMediaSurfacesINTEL).
[AVHWDeviceContext @ 0x556f1adbc8c0] Intel QSV in OpenCL release function found (clEnqueueReleaseVA_APIMediaSurfacesINTEL).
[AVHWDeviceContext @ 0x556f1adbf980] Supported validation layers:
[AVHWDeviceContext @ 0x556f1adbf980]    VK_LAYER_MESA_device_select
[AVHWDeviceContext @ 0x556f1adbf980]    VK_LAYER_MESA_overlay
[AVHWDeviceContext @ 0x556f1adbf980] GPU listing:
[AVHWDeviceContext @ 0x556f1adbf980]     0: Intel(R) Arc(tm) A380 Graphics (DG2) (discrete) (0x56a5)
[AVHWDeviceContext @ 0x556f1adbf980] Requested vendor: 0x8086
[AVHWDeviceContext @ 0x556f1adbf980] Device 0 selected: Intel(R) Arc(tm) A380 Graphics (DG2) (discrete) (0x56a5)
[AVHWDeviceContext @ 0x556f1adbf980] Queue families:
[AVHWDeviceContext @ 0x556f1adbf980]     0: graphics compute transfer (queues: 1)
[AVHWDeviceContext @ 0x556f1adbf980] Using device extension VK_KHR_push_descriptor
[AVHWDeviceContext @ 0x556f1adbf980] Using device extension VK_KHR_sampler_ycbcr_conversion
[AVHWDeviceContext @ 0x556f1adbf980] Using device extension VK_KHR_synchronization2
[AVHWDeviceContext @ 0x556f1adbf980] Using device extension VK_KHR_external_memory_fd
[AVHWDeviceContext @ 0x556f1adbf980] Using device extension VK_EXT_external_memory_dma_buf
[AVHWDeviceContext @ 0x556f1adbf980] Using device extension VK_EXT_image_drm_format_modifier
[AVHWDeviceContext @ 0x556f1adbf980] Using device extension VK_KHR_external_semaphore_fd
[AVHWDeviceContext @ 0x556f1adbf980] Using device extension VK_EXT_external_memory_host
[AVHWDeviceContext @ 0x556f1adbf980] Using device: Intel(R) Arc(tm) A380 Graphics (DG2)
[AVHWDeviceContext @ 0x556f1adbf980] Alignments:
[AVHWDeviceContext @ 0x556f1adbf980]     optimalBufferCopyRowPitchAlignment: 128
[AVHWDeviceContext @ 0x556f1adbf980]     minMemoryMapAlignment:              4096
[AVHWDeviceContext @ 0x556f1adbf980]     minImportedHostPointerAlignment:    4096
[AVHWDeviceContext @ 0x556f1adbf980] Using queue family 0 (queues: 1) for graphics compute transfers
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

root@ceb94c106c63:/# vainfo
Trying display: drm
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.18 (libva 2.18.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.6 (8589406)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP
```

### CODE REVIEW

**Comment by GoingOffRoading** [comment]
@nyanmisaka that was my thread on Reddit, and you might see this PR be rejected by Ryan due to backwards compatibility concerns.  From the Discord:

"Josh.5 — Today at 12:32 PM
Hey
[12:33 PM]
So the reason I have kept it back was because every attempt that was made to upgrade ffmpeg broke numerous people's installations on older hardware
[12:34 PM]
It is really temperamental and not having a good set of hardware testers makes it really hard to push ffmpeg updates
[12:35 PM]
I've rolled back the version a few times now because I would update it in staging branch. Tests it on a bunch of hardware, announce it for like a month and get absolutely no feedback. Then when I merge staging into master, I get a flood of issues from people who can no longer use Intel hardware acceleration
[12:35 PM]
So I just left it"

Just an FYI

What was purposed on the Discord is moving some of the items like the Jellyfin ffmpeg version number to a ENV for container deployments so that Ryan could maintain backwards compatibility, while giving the end user the choice to go forward.

Hope this helps.

**Comment by Josh5** [comment]
Thanks for responding @GoingOffRoading 

@nyanmisaka I'll keep this open for a little bit, but j believe @GoingOffRoading is coming up with a good plan to simplify the ability to select which version of ffmpeg we want to install.

**Comment by nyanmisaka** [comment]
What was the issue? It's very unlikely that ffmpeg itself has a problem. The custom ffmpeg commands may be the culprit.

The driver has been tested on Intel [KBLx, TGLx and Arc/DG2](https://github.com/intel/media-driver#supported-platforms). On the AMD side, it has been tested on Vega10 GCN and Renoir VCN2. On the NVIDIA side, it has been tested on Pascal, Turing and Ampere.

**Comment by Josh5** [comment]
Actually, this changeset contains quite a few improvements. Are you on discord? Would be keen to discuss this before merging it...

**Pull request closed without merging**
